package dev.jcrystal.crystalfash.entities;

import jcrystal.entity.types.Autogenerated;
import jcrystal.json.JsonLevel;
import jcrystal.reflection.annotations.EntityProperty;
import jcrystal.reflection.annotations.jEntity;
import jcrystal.reflection.annotations.entities.Rel1to1;
import jcrystal.server.Entity;

@jEntity
public class CartItem implements Entity.DefaultDB{
	@jcrystal.reflection.annotations.EntityKey
	private static Autogenerated id;
	
	@Rel1to1(target="items", keyLevel=JsonLevel.NORMAL)
	private static Product product;
	@EntityProperty
	private static int quantity;

/* GEN */
	protected final com.google.appengine.api.datastore.Entity rawEntity;
	public final com.google.appengine.api.datastore.Entity getRawEntity(){return rawEntity;}
	public CartItem(com.google.appengine.api.datastore.Entity rawEntity){
		this.rawEntity = rawEntity;
	}
	public CartItem(){
		rawEntity = new com.google.appengine.api.datastore.Entity(ENTITY_NAME);
	}
	protected CartItem(String entityName){
		rawEntity = new com.google.appengine.api.datastore.Entity(entityName);
	}
	public CartItem cloneFrom(CartItem from){
		this.rawEntity.setPropertiesFrom(from.rawEntity);
		return this;
	}
	public Long id(){
		return rawEntity.getKey().getId();
	}
	public CartItem put(){
		jcrystal.context.CrystalContext $ctx = jcrystal.context.CrystalContext.get();
		$ctx.DefaultDB().service.put($ctx.DefaultDB().getTxn(), rawEntity);
		return this;
	}
	public static com.google.appengine.api.datastore.Entity rawGet(com.google.appengine.api.datastore.Key $key){
		if($key == null){return null;}
		try{
			return jcrystal.context.CrystalContext.get().DefaultDB().get($key);
		}
		catch(com.google.appengine.api.datastore.EntityNotFoundException | java.lang.IllegalArgumentException e){
			return null;
		}
	}
	public static CartItem get(com.google.appengine.api.datastore.Key $key){
		com.google.appengine.api.datastore.Entity ent = rawGet($key);
		if(ent == null)return null;
		return new CartItem(ent);
	}
	public static CartItem get(Long id){
		com.google.appengine.api.datastore.Entity ent = rawGet(Key.createRawKey(id));
		if(ent == null)return null;
		return new CartItem(ent);
	}
	public static boolean exist(Long id){
		return rawGet(Key.createRawKey(id)) != null;
	}
	public static CartItem tryGet(com.google.appengine.api.datastore.Key $key){
		com.google.appengine.api.datastore.Entity ent = rawGet($key);
		if(ent == null)throw new jcrystal.utils.InternalException(17, "Invalid identifier");
		return new CartItem(ent);
	}
	public static CartItem tryGet(Long id){
		return tryGet(Key.createRawKey(id));
	}
	public static CartItem tryGet(Long id, CartItem $defValue){
		CartItem ent = get(id);
		if(ent == null)return $defValue;
		return ent;
	}
	public CartItem quantity(int quantity){
		rawEntity.setUnindexedProperty("quantity", quantity);
		return this;
	}
	public CartItem product(dev.jcrystal.crystalfash.entities.Product val){
		if(val != null){
			rawEntity.setIndexedProperty("product", val.id());
		}
		else{
			rawEntity.setIndexedProperty("product", null);
		}
		return this;
	}
	public CartItem product(Long id){
		rawEntity.setIndexedProperty("product", id);
		return this;
	}
	public int quantity(){
		return jcrystal.db.datastore.EntityUtils.getInt(rawEntity, "quantity", 0);
	}
	public Long product$Key(){
		return (Long)rawEntity.getProperty("product");
	}
	public dev.jcrystal.crystalfash.entities.Product product(){
		return dev.jcrystal.crystalfash.entities.Product.get(product$Key());
	}
	public static class CachedGetter{
		private java.util.TreeMap<Long, CartItem> cache = new java.util.TreeMap<>();
		public CartItem get(Long id){
			CartItem ret = cache.get(id);
			if(ret == null){
				cache.put(id, ret = CartItem.get(id));
			}
			return ret;
		}
	}
	public static class Post extends PostCartItem{}
	public static class Serializer extends SerializerCartItem{}
	public static QueryCartItem Query = new QueryCartItem();
	public static QueryCartItem Query(com.google.appengine.api.datastore.Key ancestor){ return new QueryCartItem(ancestor); }
	public static class Batch extends BatchCartItem{}
	public static class Meta extends MetaCartItem{}
	public static java.util.List<CartItem> convertRawList(java.util.List<com.google.appengine.api.datastore.Entity> rawData){
		if(rawData == null){return null;}
		else{
			java.util.ArrayList<CartItem> ret = new java.util.ArrayList<>();
			for(com.google.appengine.api.datastore.Entity data : rawData){
				ret.add(new CartItem(data));
			}
			return ret;
		}
	}
	public static final String ENTITY_NAME = "CartItem";
	public static class Key{
		private Key(){}
		public static com.google.appengine.api.datastore.Key cloneKey(com.google.appengine.api.datastore.Key rawKey){
			return CartItem.Key.createRawKey(rawKey.getId());
		}
		public static com.google.appengine.api.datastore.Key createRawKey(String entityName, Long id){
			if(id == null){
				return null;
			}
			return com.google.appengine.api.datastore.KeyFactory.createKey(entityName, id);
		}
		public static com.google.appengine.api.datastore.Key createRawKey(Long id){
			if(id == null){
				return null;
			}
			return com.google.appengine.api.datastore.KeyFactory.createKey(ENTITY_NAME, id);
		}
		public static final Long getId(com.google.appengine.api.datastore.Key rawKey){
			return rawKey.getId();
		}
	}
/* END */
}
